<div style="line-height:0.5">
<h1 style="color:#BF66F2 ">  Tensors in PyTorch 2 </h1>
<h4> Slicing, Permutating, and Converting.  </h4> 
<div style="margin-top: -10px;">
<span style="display: inline-block;">
    <h3 style="color: lightblue; display: inline;">Keywords:</h3>
    torch.randn() + torch.stack() + torch.sum() + torch.allclose()
</span>
</div>
</div>

In [2]:
# Ignore CUDA warnings when GPU is not in use
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [3]:
import torch
import numpy as np
import pandas as pd
import tensorflow as tf

In [17]:
""" Perform tensor operations.
N.B.
Using 'multiplied_tensor = reshaped_tensor * random_tensor' will lead to a "RuntimeError! due to sizes mismatch."
"""

zeros_tensor = torch.zeros((2, 3))
ones_tensor = torch.ones((2, 3))
random_tensor = torch.rand((3, 2))
custom_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

sliced_tensor = custom_tensor[:, 1:]
added_tensor = custom_tensor + ones_tensor
reshaped_tensor = custom_tensor.reshape((2, 3))

# Transpose random_tensor to make the multiplication valid
random_tensor_transposed = random_tensor.T  

# Perform element-wise multiplication
multiplied_tensor = reshaped_tensor * random_tensor_transposed

print(reshaped_tensor)
print(sliced_tensor)
print(added_tensor)
print(multiplied_tensor)

In [32]:
""" Dot product between tensors
N.B.
Using 'dot_product = torch.mm(custom_tensor, random_tensor)' will lead to #RuntimeError: expected scalar type Long but found Float
It is neccesary to create "Long" tensors.
random_tensor = torch.randint(0, 10, (3, 2), dtype=torch.long)  
custom_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.long)
""" 

## Convert existing tensors to dtype=torch.long, to permit product calculation
random_tensor = random_tensor.to(dtype=torch.long)
custom_tensor = custom_tensor.to(dtype=torch.long)

dot_product = torch.mm(custom_tensor, random_tensor)
dot_product

tensor([[16, 23],
        [40, 65]])

<h4 style="color:#BF66F2 ">  => Transpose: </h4>

In [62]:
x = torch.tensor([[1, 2], [3, 4]])
y = x.t()
x, y

(tensor([[1, 2],
         [3, 4]]),
 tensor([[1, 3],
         [2, 4]]))

<h4 style="color:#BF66F2 ">  => Permute: </h4>

In [63]:
x = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
y = x.permute(2, 0, 1)
x, y

(tensor([[[1, 2],
          [3, 4]],
 
         [[5, 6],
          [7, 8]]]),
 tensor([[[1, 3],
          [5, 7]],
 
         [[2, 4],
          [6, 8]]]))

<h4 style="color:#BF66F2 ">  => Views: </h4>

In [33]:
""" Reshape """
x = torch.tensor([1, 2, 3, 4])
y = x.view(2, 2)
print(y)

tensor([[1, 2],
        [3, 4]])


In [65]:
""" Add a dimension, from 1d to 2d """
x = torch.arange(6)
y = x.view(2, 3)
x,y

(tensor([0, 1, 2, 3, 4, 5]),
 tensor([[0, 1, 2],
         [3, 4, 5]]))

In [66]:
""" Reshape with Inferred second dimension """
x = torch.tensor([1, 2, 3, 4, 5, 6])
y = x.view(2, -1)  
x,y

(tensor([1, 2, 3, 4, 5, 6]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

In [67]:
""" Nested view """
x = torch.tensor([1, 2, 3, 4, 5, 6])
y = x.view(2, 3)
z = y.view(3, 2)
x,y,z

(tensor([1, 2, 3, 4, 5, 6]),
 tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 2],
         [3, 4],
         [5, 6]]))

In [68]:
## Clone with View
x = torch.tensor([1, 2, 3, 4])
y = x.clone().view(2, 2)
x,y

(tensor([1, 2, 3, 4]),
 tensor([[1, 2],
         [3, 4]]))

In [69]:
""" Squeeze and Unsqueeze """
x = torch.tensor([1, 2, 3, 4])
y = x.view(2, 2)
# Add a dimension
z = y.unsqueeze(0)  
x,y,z 

(tensor([1, 2, 3, 4]),
 tensor([[1, 2],
         [3, 4]]),
 tensor([[[1, 2],
          [3, 4]]]))

In [70]:
""" Flatten a 3D Tensor """
x = torch.randn(2, 3, 4)
y = x.view(x.size(0), -1)
x,y

(tensor([[[-1.1812,  0.8232, -1.6328, -0.3370],
          [ 2.0581, -0.8308,  2.0918, -0.4919],
          [-0.5943, -0.9565,  0.4792, -0.7039]],
 
         [[-1.1146, -0.1058, -0.6221, -0.9684],
          [ 0.1239, -0.6627,  0.0068, -1.7819],
          [ 0.6685,  0.5804, -1.2789, -1.3036]]]),
 tensor([[-1.1812,  0.8232, -1.6328, -0.3370,  2.0581, -0.8308,  2.0918, -0.4919,
          -0.5943, -0.9565,  0.4792, -0.7039],
         [-1.1146, -0.1058, -0.6221, -0.9684,  0.1239, -0.6627,  0.0068, -1.7819,
           0.6685,  0.5804, -1.2789, -1.3036]]))

In [71]:
""" Permute and View. """
x = torch.randn(2, 3, 4)
y = x.permute(0, 2, 1).contiguous().view(2, -1)
x,y

(tensor([[[ 0.3997,  1.9782,  0.7129,  0.0671],
          [ 0.1556,  0.8556, -0.9329,  0.6139],
          [-1.4615,  0.2474, -0.9193,  0.2619]],
 
         [[-0.1116, -1.3887,  1.0781, -1.3559],
          [-1.0864,  0.7510,  0.0152,  0.4619],
          [ 0.6258,  0.3474, -0.0213,  1.1622]]]),
 tensor([[ 0.3997,  0.1556, -1.4615,  1.9782,  0.8556,  0.2474,  0.7129, -0.9329,
          -0.9193,  0.0671,  0.6139,  0.2619],
         [-0.1116, -1.0864,  0.6258, -1.3887,  0.7510,  0.3474,  1.0781,  0.0152,
          -0.0213, -1.3559,  0.4619,  1.1622]]))

In [89]:
""" Batch Matrix Multiplication.
N.B.
Matrix multiplication and reshaping operations must be compatible. 
The result of the bmm operation has 32 elements => it can be reshaped into a shape that has the same number of elements.
"""
x = torch.randn(2, 3, 4)
y = torch.randn(2, 4, 3)
result_bmm = torch.bmm(x.view(-1, 4, 3), y.view(-1, 3, 4)).view(2, 4, 4)
result_bmm

tensor([[[ 0.4088,  1.0336,  0.5344,  0.4636],
         [-0.3784, -3.0223,  0.2899, -2.9596],
         [-0.5313, -0.4152, -0.0172, -0.0940],
         [ 0.0155, -0.7898,  0.1070, -0.8587]],

        [[ 0.4704,  0.2189,  0.0267, -0.3712],
         [-1.1777,  0.6148,  1.1800,  0.3318],
         [-1.2264,  1.5978,  2.0141, -0.3041],
         [-0.7252, -0.1474, -0.1350,  0.2805]]])

<h4 style="color:#BF66F2 ">  => Equality: </h4>

In [34]:
# eq
torch.eq(torch.tensor([[1., 2.], [3., 4.]]), torch.tensor([[1., 1.], [4., 4.]]))

tensor([[ True, False],
        [False,  True]])

In [35]:
# equal
print(torch.equal(torch.tensor([[1., 2.], [3, 4.]]), torch.tensor([[1., 1.], [4., 4.]])))
print(torch.equal(torch.tensor([[1., 2.], [3., 4.]]), torch.tensor([[1., 2.], [3., 4.]])))

False
True


In [36]:
""" Check if all elements of two tensors are close to each other within some tolerance.
Tolerance => atol + rtol * abs(tensor2)
where:
- atol absolute tolerance           [default val 1e-08 => 0.00000001]
- rtol is the relative tolerance    [default val 1e-08]
"""
torch.allclose(torch.tensor([[1., 2.], [3., 4.]]), torch.tensor([[1., 2.000000001], [3., 4.]]))

True

<h4 style="color:#BF66F2 ">  => From tensorFlow to PyTorch: </h4>

In [45]:
tensor1 = tf.constant(7)
tensor2 = tf.constant(7)
tensor3 = tf.ones(shape=(7,))
tensor4 = tf.ones(shape=(7,))
tensor5 = tf.zeros(shape=(9,))

print(tensor1)
print(tensor2)

tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)


In [47]:
## Compare tensors
result12 = tf.equal(tensor1, tensor2)
result34 = tf.equal(tensor3, tensor4)

result12, result34

(<tf.Tensor: shape=(), dtype=bool, numpy=True>,
 <tf.Tensor: shape=(7,), dtype=bool, numpy=array([ True,  True,  True,  True,  True,  True,  True])>)

In [49]:
"""  Convert the tensors to PyTorch tensors. """
ten3 = torch.tensor(tensor3.numpy())
ten4 = torch.tensor(tensor4.numpy())
ten5 = torch.tensor(tensor5.numpy())

print(tensor3, ten3)
print(tensor4, ten4)
print(tensor5, ten5)

tf.Tensor([1. 1. 1. 1. 1. 1. 1.], shape=(7,), dtype=float32) tensor([1., 1., 1., 1., 1., 1., 1.])
tf.Tensor([1. 1. 1. 1. 1. 1. 1.], shape=(7,), dtype=float32) tensor([1., 1., 1., 1., 1., 1., 1.])
tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(9,), dtype=float32) tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [42]:
""" Calculate the percentage of elements that are equal. """
print(torch.sum(torch.eq(tensor3, tensor4)).item()/tensor3.nelement())

1.0


<h4 style="color:#BF66F2 ">  => Concatenate: </h4>

In [75]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
z = torch.cat((x, y), dim=0)
z

tensor([1, 2, 3, 4, 5, 6])

In [76]:
z.dim()

1

In [106]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

zz = torch.tensor([[7], [8], [9]])
# Reshape y to have the same shape as the rows of z
y_expanded = y.view(-1, 1)

# Perform element-wise addition
q = zz + y

y.shape, zz.shape, y_expanded.shape, q

tensor([[11, 12, 13],
        [12, 13, 14],
        [13, 14, 15]])


In [107]:
# Slicing (using whatever number greater than 1)
print(q[:643])

tensor([[11, 12, 13],
        [12, 13, 14],
        [13, 14, 15]])


<h4 style="color:#BF66F2 ">  => Slicing: </h4>

In [54]:
t1 = torch.tensor([1,2,3,4,5]) 
t2 = torch.tensor([[1,2,3],[4,5,6]])
t3 = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])

t1[1:4], t2[:,1], t3[::,1,1]

(tensor([2, 3, 4]), tensor([2, 5]), tensor([4, 8]))

In [55]:
# Negative indexing
t4 = torch.randn(4,3)
t4, t4.dim(), t4[-1:]

(tensor([[ 2.0328, -0.1112,  1.3843],
         [ 1.0001, -0.2679, -1.1346],
         [-0.0598,  0.0492, -1.3476],
         [ 0.2015,  0.2634, -0.3964]]),
 2,
 tensor([[ 0.2015,  0.2634, -0.3964]]))

In [56]:
# Skip elements
t5 = torch.randn(5,5,5) 
t5[::2,:,:]

tensor([[[-1.5597, -0.2001, -0.3670,  1.1898, -1.3164],
         [-0.7738, -0.5546, -0.6210, -2.1632,  1.5810],
         [-0.7321, -1.4175,  0.1097,  0.9072,  0.2233],
         [ 0.8454, -0.2556, -0.9642,  0.3502,  2.4169],
         [ 1.4442, -1.4146, -1.5604,  1.3196,  0.8837]],

        [[-1.6367, -2.1349, -0.3863,  1.2212, -0.5606],
         [-1.7655, -1.1650,  1.1667,  0.6932,  0.0084],
         [ 1.1665, -0.4275,  0.3919,  0.6940, -1.5913],
         [ 0.3855,  1.6351, -0.3890,  1.1391, -1.4347],
         [-0.2662,  1.6332, -1.7744,  0.2900, -0.5376]],

        [[ 0.6745,  0.0698,  2.3746, -1.6766,  1.2339],
         [ 0.7886, -1.1450,  0.0675, -0.1048, -0.0711],
         [-1.9525, -0.7117, -0.4527, -0.4212, -0.0189],
         [-2.6939,  0.1455,  0.6829, -0.5073, -0.5686],
         [ 1.1843,  1.3195,  0.1054, -1.0410, -1.6503]]])

In [57]:
# Multidimensional slice
t6 = torch.randn(3,4,5)
t6[1:3, 1:, :2]

tensor([[[-0.2676, -0.5557],
         [ 0.9558,  1.9563],
         [ 1.4871,  0.2636]],

        [[ 1.7563, -0.3373],
         [-1.2125,  1.6479],
         [-0.1627,  0.7981]]])

In [58]:
""" Stack """
### Sequence of tensors (must have the same size)
t1 = torch.tensor([[1,2,3], [4,5,6]]) 
t2 = torch.tensor([[7,8,9], [10,11,12]])
t3 = torch.tensor([[13,14,15], [16,17,18]])

# Stack tensors along a new dimension           
t7 = torch.stack((t1, t2, t3), dim=0)
t7.shape, t7[:,1]

(torch.Size([3, 2, 3]),
 tensor([[ 4,  5,  6],
         [10, 11, 12],
         [16, 17, 18]]))

In [59]:
# Slice and step
t8 = torch.randn(10,20,30)
t8[::3,::2,::5]

tensor([[[ 0.2245, -0.0567, -0.2195, -1.1520,  1.3534, -0.3623],
         [ 0.9551,  0.3386,  0.0992,  1.1884,  0.4604,  1.0712],
         [-0.3540, -0.1760, -0.7404, -0.8590,  0.3397,  0.1583],
         [-1.5235,  0.9464, -0.5895,  0.3317, -1.8394,  0.7540],
         [-0.9072,  0.1099, -0.1008, -0.2263,  0.3370, -0.3760],
         [-0.6148, -0.2064, -2.4971,  1.5091,  0.2511, -1.3313],
         [-1.2007, -0.2711,  0.1316, -0.4046,  1.2316,  1.7293],
         [ 0.2079,  0.5154, -0.2842, -0.6503, -0.6726, -1.4182],
         [-0.8555,  0.4968, -0.3908,  1.1459, -1.0014,  0.6994],
         [-0.2164,  0.1291,  0.9052, -0.0919,  1.4075, -1.1930]],

        [[-0.1908, -0.4879, -0.3150, -1.1580,  1.9536,  0.1861],
         [ 0.4766, -0.6017,  0.2823,  0.9599, -0.4215, -0.9887],
         [-0.9419, -0.7010, -0.3153, -0.7508, -1.8411,  1.0687],
         [ 0.1258,  0.4008, -1.8636,  0.9739, -0.6943,  1.7665],
         [-1.6353, -0.1708, -0.6436, -0.0708, -1.4541,  0.3976],
         [ 1.0065,  1.6

In [60]:
""" Dynamic slice """
t9 = torch.rand(3,4)
slices = torch.tensor([0, 2]).long()
t9[slices] 

tensor([[0.4416, 0.5405, 0.4767, 0.4347],
        [0.6419, 0.0426, 0.9762, 0.5671]])

In [61]:
# Assign value to sliced
t10 = torch.tensor([[1,2,3],[4,5,6]])
t10[...,1] = 0
t10

tensor([[1, 0, 3],
        [4, 0, 6]])