<div style="line-height:0.5">
<h1 style="color:#BF66F2 ">  Tensors in PyTorch 1 </h1>
<h4> Reshaping, Striding, and Manipulating tensors. </h4> 
<div style="margin-top: 4px;">
<span style="display: inline-block;">
    <h3 style="color: lightblue; display: inline;">Keywords:</h3>
    %%time magic command + torch.optim + torch.multiply + torch.randn + warnings.simplefilter("ignore")
</span>
</div>
</div>



In [2]:
!python --version

Python 3.10.9


In [3]:
import torch
import warnings
import numpy as np
import pandas as pd

In [3]:
""" Create empty tensors => x = torch.empty#(size of dimensions) """
x = torch.empty(1)
y = torch.empty(3)
z = torch.empty(2,3,4,5,2)  
q = torch.ones(2,2, dtype=torch.int16)
s = torch.diag(torch.tensor([1,2,3,4,5]))
e = torch.eye(3)
a = torch.arange(1, 8, 2)
l = torch.linspace(0, 1, 5)
print(x)
print(y)
#print(z)
print(s)
print(e)
print(a)
print(l)

tensor([1.8393e+25])
tensor([-4.3735e-07,  4.5843e-41,  7.8338e-35])
tensor([[1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0],
        [0, 0, 0, 0, 5]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([1, 3, 5, 7])
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [9]:
# 0)
ten = torch.tensor([2.5, 0], dtype=torch.float16) 
ten 

tensor([2.5000, 0.0000], dtype=torch.float16)

In [10]:
# 1) From Numpy array
arra = np.array([1, 2, 3, 4, 5])
ten_num = torch.from_numpy(arra) #also ten_num change!! 
xx = ten_num
x_np = xx.numpy()
arra += 1

print(f"ten_num array = {ten_num}")
print(x_np) #also this change!
print(ten)

ten_num array = tensor([2, 3, 4, 5, 6])
[2 3 4 5 6]
tensor([2.5000, 0.0000], dtype=torch.float16)


In [11]:
# 2) From Pandas dataframe
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4], 'C': [5, 6]})
xdf = torch.tensor(df.values)
print(f"xdf = {xdf}")

xdf = tensor([[1, 3, 5],
        [2, 4, 6]])


In [12]:
# 3) From a list of lists:
x_list = [[1, 2, 3], [4, 5, 6]]
xl = torch.tensor(x_list)
print(f"xl = {xl}")

xl = tensor([[1, 2, 3],
        [4, 5, 6]])


In [13]:
# 4) Randomly generated tensor with a given shape:
rx = torch.randn((2, 3))
print(f"rx = {rx}")

rx = tensor([[-1.4989,  1.3164, -1.8248],
        [ 1.0753, -0.7757, -0.3708]])


In [14]:
# 5)
ranten = torch.rand(4, 5)
print(ranten)
print(ranten.ndim)
print(ranten.shape)
print(ranten.names)
print(ranten[2])
ra2 = ranten.transpose(0,1)
ra2

tensor([[0.2293, 0.2179, 0.5171, 0.4198, 0.2406],
        [0.1794, 0.5975, 0.0716, 0.4121, 0.9055],
        [0.9797, 0.9055, 0.7710, 0.9138, 0.3979],
        [0.3785, 0.2866, 0.2086, 0.0080, 0.6578]])
2
torch.Size([4, 5])
(None, None)
tensor([0.9797, 0.9055, 0.7710, 0.9138, 0.3979])


tensor([[0.2293, 0.1794, 0.9797, 0.3785],
        [0.2179, 0.5975, 0.9055, 0.2866],
        [0.5171, 0.0716, 0.7710, 0.2086],
        [0.4198, 0.4121, 0.9138, 0.0080],
        [0.2406, 0.9055, 0.3979, 0.6578]])

In [15]:
# 6) Rand
ranten = torch.rand(1, 3, 5)
print(ranten)
print(ranten.ndim)
print(ranten.shape)
print(ranten.names)
print(ranten[0])

tensor([[[0.0654, 0.0426, 0.4027, 0.4002, 0.9435],
         [0.3784, 0.7279, 0.0553, 0.9930, 0.9732],
         [0.2259, 0.6959, 0.8427, 0.2963, 0.4022]]])
3
torch.Size([1, 3, 5])
(None, None, None)
tensor([[0.0654, 0.0426, 0.4027, 0.4002, 0.9435],
        [0.3784, 0.7279, 0.0553, 0.9930, 0.9732],
        [0.2259, 0.6959, 0.8427, 0.2963, 0.4022]])


In [16]:
# 7)
ra1 = torch.rand(1, 3, 224, 224)
print()
print(ra1.ndim)
print(ra1.shape)
print(ra1.size())       # same as shape
print(ra1[:, 1])
print(ra1.dtype)
print(ra1.device)       # total number of elements in the tensor.
print(ra1.numel())


4
torch.Size([1, 3, 224, 224])
torch.Size([1, 3, 224, 224])
tensor([[[0.7595, 0.8329, 0.2097,  ..., 0.8284, 0.4403, 0.5561],
         [0.4182, 0.9320, 0.7243,  ..., 0.6176, 0.0155, 0.1564],
         [0.4568, 0.0991, 0.2384,  ..., 0.5284, 0.7979, 0.9997],
         ...,
         [0.6376, 0.2030, 0.3721,  ..., 0.9531, 0.8573, 0.9872],
         [0.2176, 0.6084, 0.8702,  ..., 0.9452, 0.4859, 0.3221],
         [0.2888, 0.5912, 0.7806,  ..., 0.4225, 0.7269, 0.1247]]])
torch.float32
cpu
150528


In [17]:
# 8) Copy tensors #1
""" 
N.B.
- 'yy = ra1' => 'yy' and 'ra1' refer to the same tensor object in memory. 
Callling 'yy.add(1)' means to generate a new tensor with the values of ra1 incremented by 1, 
but without modify 'ra1' or yy in-place. Use ra1.add_(1) to modify 'ra1' in-place
"""
yy = ra1
yy.add(1)
ra1

tensor([[[[0.8773, 0.4463, 0.6021,  ..., 0.6001, 0.3332, 0.0326],
          [0.0520, 0.8049, 0.1437,  ..., 0.2140, 0.8957, 0.7976],
          [0.1086, 0.9595, 0.0905,  ..., 0.7239, 0.6051, 0.1180],
          ...,
          [0.8789, 0.2816, 0.7663,  ..., 0.2017, 0.7507, 0.3057],
          [0.1852, 0.7399, 0.7758,  ..., 0.0053, 0.9536, 0.8370],
          [0.2895, 0.1455, 0.0787,  ..., 0.4001, 0.3740, 0.3242]],

         [[0.7595, 0.8329, 0.2097,  ..., 0.8284, 0.4403, 0.5561],
          [0.4182, 0.9320, 0.7243,  ..., 0.6176, 0.0155, 0.1564],
          [0.4568, 0.0991, 0.2384,  ..., 0.5284, 0.7979, 0.9997],
          ...,
          [0.6376, 0.2030, 0.3721,  ..., 0.9531, 0.8573, 0.9872],
          [0.2176, 0.6084, 0.8702,  ..., 0.9452, 0.4859, 0.3221],
          [0.2888, 0.5912, 0.7806,  ..., 0.4225, 0.7269, 0.1247]],

         [[0.5388, 0.0149, 0.8761,  ..., 0.0285, 0.4097, 0.9484],
          [0.6749, 0.0577, 0.0962,  ..., 0.0225, 0.5456, 0.2823],
          [0.1371, 0.4029, 0.1710,  ..., 0

In [18]:
# 9) Copy tensors #2 => Views
x1 = torch.randn(2, 3, 4)

# Reshape the tensor to have shape (3, 8)
y1 = x1.view(3, 8) 
print(x1.shape)
print(y1.shape)
y2 = x1.transpose(0, 2)
print(x1.shape)
print(y2.shape) 
print()
print(x1)
print()
print(y2)

torch.Size([2, 3, 4])
torch.Size([3, 8])
torch.Size([2, 3, 4])
torch.Size([4, 3, 2])

tensor([[[ 1.5979,  0.8161,  0.0935,  0.2026],
         [ 0.5049,  0.5279, -0.4712,  1.1922],
         [ 0.6317,  0.1504,  0.5426,  0.8935]],

        [[ 0.3370, -0.3175,  2.1700,  0.4758],
         [ 0.4339, -0.4590,  0.0279,  0.1146],
         [ 0.3633,  0.4099,  0.7050,  1.3141]]])

tensor([[[ 1.5979,  0.3370],
         [ 0.5049,  0.4339],
         [ 0.6317,  0.3633]],

        [[ 0.8161, -0.3175],
         [ 0.5279, -0.4590],
         [ 0.1504,  0.4099]],

        [[ 0.0935,  2.1700],
         [-0.4712,  0.0279],
         [ 0.5426,  0.7050]],

        [[ 0.2026,  0.4758],
         [ 1.1922,  0.1146],
         [ 0.8935,  1.3141]]])


In [19]:
# 10) Reshape the tensor to have shape (6, 4)
y3 = x1.reshape(6, 4) 
print(x1.shape)
print(x1)
print()
print(y3)
print(y3.shape)

torch.Size([2, 3, 4])
tensor([[[ 1.5979,  0.8161,  0.0935,  0.2026],
         [ 0.5049,  0.5279, -0.4712,  1.1922],
         [ 0.6317,  0.1504,  0.5426,  0.8935]],

        [[ 0.3370, -0.3175,  2.1700,  0.4758],
         [ 0.4339, -0.4590,  0.0279,  0.1146],
         [ 0.3633,  0.4099,  0.7050,  1.3141]]])

tensor([[ 1.5979,  0.8161,  0.0935,  0.2026],
        [ 0.5049,  0.5279, -0.4712,  1.1922],
        [ 0.6317,  0.1504,  0.5426,  0.8935],
        [ 0.3370, -0.3175,  2.1700,  0.4758],
        [ 0.4339, -0.4590,  0.0279,  0.1146],
        [ 0.3633,  0.4099,  0.7050,  1.3141]])
torch.Size([6, 4])


In [20]:
# 11) Remove dimensions of size 1 from the tensor.
x2 = torch.randn(1, 3, 1, 4) 
y4 = x2.squeeze()
print(x2)
print(x2.shape)
print(y4)
print(y4.shape)

tensor([[[[ 1.3790, -0.5328,  0.7471, -0.9571]],

         [[-0.5873, -0.6424, -0.3490, -1.2817]],

         [[-0.0945, -0.7134,  0.8987, -0.8470]]]])
torch.Size([1, 3, 1, 4])
tensor([[ 1.3790, -0.5328,  0.7471, -0.9571],
        [-0.5873, -0.6424, -0.3490, -1.2817],
        [-0.0945, -0.7134,  0.8987, -0.8470]])
torch.Size([3, 4])


In [21]:
# 12) Add dimensions of size 1 to the tensor for 0 and 2 position
x3 = torch.randn(3, 4)
y5 = x3.unsqueeze(0).unsqueeze(2) 
print(x3)
print(x3.shape)
print(y5)
print(y5.shape)

tensor([[ 0.8041, -1.1978, -0.8636, -0.7963],
        [ 0.6860,  1.8731, -0.4374, -0.0574],
        [ 0.1817, -0.2148,  0.0285,  1.6633]])
torch.Size([3, 4])
tensor([[[[ 0.8041, -1.1978, -0.8636, -0.7963]],

         [[ 0.6860,  1.8731, -0.4374, -0.0574]],

         [[ 0.1817, -0.2148,  0.0285,  1.6633]]]])
torch.Size([1, 3, 1, 4])


In [22]:
yy.add_(1)  #also the original tensor change!
yy
ra1

tensor([[[[1.8773, 1.4463, 1.6021,  ..., 1.6001, 1.3332, 1.0326],
          [1.0520, 1.8049, 1.1437,  ..., 1.2140, 1.8957, 1.7976],
          [1.1086, 1.9595, 1.0905,  ..., 1.7239, 1.6051, 1.1180],
          ...,
          [1.8789, 1.2816, 1.7663,  ..., 1.2017, 1.7507, 1.3057],
          [1.1852, 1.7399, 1.7758,  ..., 1.0053, 1.9536, 1.8370],
          [1.2895, 1.1455, 1.0787,  ..., 1.4001, 1.3740, 1.3242]],

         [[1.7595, 1.8329, 1.2097,  ..., 1.8284, 1.4403, 1.5561],
          [1.4182, 1.9320, 1.7243,  ..., 1.6176, 1.0155, 1.1564],
          [1.4568, 1.0991, 1.2384,  ..., 1.5284, 1.7979, 1.9997],
          ...,
          [1.6376, 1.2030, 1.3721,  ..., 1.9531, 1.8573, 1.9872],
          [1.2176, 1.6084, 1.8702,  ..., 1.9452, 1.4859, 1.3221],
          [1.2888, 1.5912, 1.7806,  ..., 1.4225, 1.7269, 1.1247]],

         [[1.5388, 1.0149, 1.8761,  ..., 1.0285, 1.4097, 1.9484],
          [1.6749, 1.0577, 1.0962,  ..., 1.0225, 1.5456, 1.2823],
          [1.1371, 1.4029, 1.1710,  ..., 1

In [23]:
# 13) Create tensor with same data as ra1, but with its own memory not a shared one!
z = ra1.clone()
z[0, 0, 0, 0] = 7.0
ra1

tensor([[[[1.8773, 1.4463, 1.6021,  ..., 1.6001, 1.3332, 1.0326],
          [1.0520, 1.8049, 1.1437,  ..., 1.2140, 1.8957, 1.7976],
          [1.1086, 1.9595, 1.0905,  ..., 1.7239, 1.6051, 1.1180],
          ...,
          [1.8789, 1.2816, 1.7663,  ..., 1.2017, 1.7507, 1.3057],
          [1.1852, 1.7399, 1.7758,  ..., 1.0053, 1.9536, 1.8370],
          [1.2895, 1.1455, 1.0787,  ..., 1.4001, 1.3740, 1.3242]],

         [[1.7595, 1.8329, 1.2097,  ..., 1.8284, 1.4403, 1.5561],
          [1.4182, 1.9320, 1.7243,  ..., 1.6176, 1.0155, 1.1564],
          [1.4568, 1.0991, 1.2384,  ..., 1.5284, 1.7979, 1.9997],
          ...,
          [1.6376, 1.2030, 1.3721,  ..., 1.9531, 1.8573, 1.9872],
          [1.2176, 1.6084, 1.8702,  ..., 1.9452, 1.4859, 1.3221],
          [1.2888, 1.5912, 1.7806,  ..., 1.4225, 1.7269, 1.1247]],

         [[1.5388, 1.0149, 1.8761,  ..., 1.0285, 1.4097, 1.9484],
          [1.6749, 1.0577, 1.0962,  ..., 1.0225, 1.5456, 1.2823],
          [1.1371, 1.4029, 1.1710,  ..., 1

In [24]:
# 14) Create a random tensor with a similar shape to an image tensor
rand_image_tensor = torch.rand(size=(3, 224, 224))    #(height, widht, colour channels)
print(rand_image_tensor.ndim)
print(rand_image_tensor.shape)

3
torch.Size([3, 224, 224])


In [25]:
# 15)
""" Create a range of tensors and tensors-like.
N.B
Do not use 'a_tens = torch.range(0,10)' since 'torch.range' is deprecated !
"""
a_tens = torch.arange(0.0 ,10.0)
b_tens = torch.zeros_like(a_tens)
c_tens = torch.rand_like(a_tens)
print(a_tens)
print(b_tens)
print(c_tens)
print(f'stride of c_tens is {c_tens.stride()}')

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0.8350, 0.8575, 0.5386, 0.4283, 0.1917, 0.5022, 0.8101, 0.7854, 0.7712,
        0.4309])
stride of c_tens is (1,)


<h3 style="color:#BF66F2 "> Recap: Stride </h3>
<div style="margin-top: -8px;">
The stride of a tensor is a tuple of integers that specifies the number of elements to step in each dimension when traversing the tensor. <br>
It represents the number of bytes between adjacent elements in memory for each dimension of the tensor.

**Example:** <br>
Consider a PyTorch tensor x with shape (13, 4124, 545, 6546, 123). <br>
The stride of x can be calculated as follows: <br>
1) The stride for the last (innermost) dimension is always 1. <br>
This is because elements along the innermost dimension are stored contiguously in memory, so the stride between adjacent elements <br> is simply the size of one element, which is 1. <br>
2) For the fourth dimension, the stride is the number of elements between adjacent elements along that dimension. <br>
In this case, x has 6546 elements along the fourth dimension, so the stride along that dimension is 123 * 1 = 123.
3) For the third dimension, the stride is the number of elements between adjacent elements along that dimension. <br>
In this case, x has 545 elements along the third dimension, and each block of 6546 elements along the fourth dimension is 123 elements apart, <br> so the stride along the third dimension is 6546 * 123 = 804858. <br>
4) For the second dimension, the stride is the number of elements between adjacent elements along that dimension. <br>
In this case, x has 4124 elements along the second dimension, and each block of 545 elements along the third dimension is 804858 elements apart, <br> so the stride along the second dimension is 545 * 804858 = 438829190.
5) For the first (outermost) dimension, the stride is the number of elements between adjacent elements along that dimension. <br>
In this case, x has 13 elements along the first dimension, and each block of 4124 elements along the second dimension is 438829190 elements apart, <br> so the stride along the first dimension is 4124 * 438829190 = 1.806e+12. <br>

Hence, the STRIDE of x is: (1, 123, 804858, 438829190, 180598125960)
</div>

In [26]:
""" Here the tensor has 2 dimentions. size (2,3)
The first (outermost) dimension has size 2 and the second (innermost) dimension has size 3.
The stride for the last (innermost) dimension of a PyTorch tensor is always 1, regardless of the size of the other dimensions. 
This is because adjacent elements in memory along the innermost dimension are stored contiguously, 
so the stride between them is simply the size of one element.
"""
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
stride = x.stride()
print("stride:", stride)

stride: (3, 1)


In [8]:
""" Create random tensors with values drawn from a normal distribution. """
x1 = torch.randn(3, requires_grad=True) 
x = torch.randn(1, 3, 4, 2, requires_grad=True) 
y = x + 2
z = y*y*2

z = z.mean(dim=(0, 1, 2, 3))
print(x1)
print(x)
#print(y)
#print(z)

tensor([0.7273, 1.3169, 0.2948], requires_grad=True)
tensor([[[[ 0.6988, -0.2432],
          [-1.1648, -2.7377],
          [ 0.6026, -2.1569],
          [-0.2726,  0.1849]],

         [[ 0.5109,  0.2411],
          [-0.5887, -1.4085],
          [ 0.5020,  0.4002],
          [-0.6306,  1.0168]],

         [[-0.5062,  1.0458],
          [ 1.1618,  0.5608],
          [-0.3831,  0.0402],
          [-0.1679,  0.6867]]]], requires_grad=True)


In [28]:
# Reshape from dim 1 to dim 2
d_tens = torch.reshape(c_tens,(2,5)) 
d_tens.ndim

2

In [29]:
""" Crete a tensors with specific type [float 32]. """
fl32_tens = torch.tensor([41.0, 63.0, 19.0],
                        #dtype=torch.float16,
                        #dtype=torch.float32,
                        #dtype=torch.float64,
                        dtype=torch.float,          # corresponds to => torch.float32
                        #dtype=float,               # corresponds to => torch.float64 == torch.double
                        device=None, 
                        requires_grad=False
                        )
fl32_tens

tensor([41., 63., 19.])

In [30]:
int16_tens = torch.tensor([1,2,3], dtype=torch.int16)
int32_tens = torch.tensor([1,2,3], dtype=torch.int32)
res = int32_tens * int16_tens
print(res.dtype)
res1 = int16_tens * fl32_tens
print(res1)
print(f"Shape of tensor: {res1.shape}")
print(f"Datatype of tensor: {res1.dtype}")
print(f"Device tensor is stored on: {res1.device}")

torch.int32
tensor([ 41., 126.,  57.])
Shape of tensor: torch.Size([3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


<h2 style="color:#BF66F2 ">  Tensor manipulations </h2>

In [31]:
""" Operations on tensors.
N.B. 
Tensors don't change unless reassigned!  
Doing ten + 10 ... ten * 10  does not modify the tensor."""
tensor_mani = torch.tensor([1, 2, 3])
tensor_mani2 = torch.tensor([1, 2, 3])
tensor_mani = tensor_mani + 3 
tensor_mani = tensor_mani * 2
tensor_mani = tensor_mani - 4
tensor_mani = tensor_mani / 2
tensor_mani3 = tensor_mani // 2
tensor_mani4 = tensor_mani * tensor_mani2
print(tensor_mani)
print(tensor_mani2)
print(tensor_mani3)
print(tensor_mani4)

# Try a torch function
te5 = torch.multiply(tensor_mani4, 10) 
print(tensor_mani4)
print(te5)

tensor([2., 3., 4.])
tensor([1, 2, 3])
tensor([1., 1., 2.])
tensor([ 2.,  6., 12.])
tensor([ 2.,  6., 12.])
tensor([ 20.,  60., 120.])


In [32]:
""" Multiplication
- Element-wise multiplication	[1*1, 2*2, 3*3] = [1, 4, 9]	tensor * tensor
- Matrix multiplication	[1*1 + 2*2 + 3*3] = [14]	tensor.matmul(tensor)
"""
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
mat_tensor = torch.tensor([1, 2, 3])
print(tensor_mani, * te5)
print(mat_tensor)
print(f"mat_tensor.shape is \"{mat_tensor.shape}\"")
mat_mat = mat_tensor * mat_tensor
print(mat_mat)
print()
# Matrix multiplication 1
print(torch.matmul(mat_tensor, mat_tensor)) 
# Matrix multiplication 2 using "@" symbol (though not recommended) 
print(mat_tensor @ mat_tensor)

tensor([2., 3., 4.]) tensor(20.) tensor(60.) tensor(120.)
tensor([1, 2, 3])
mat_tensor.shape is "torch.Size([3])"
tensor([1, 4, 9])

tensor(14)
tensor(14)


In [33]:
%%time
""" Matrix multiplication by hand.
N.B.
It is always not recommended doing operations with 'for' statements, when not strictly necessary, \\
since loops are computationally expensive """
value = 0
for i in range(len(mat_tensor)):
  value += mat_tensor[i] * mat_tensor[i]
value

CPU times: user 1.32 ms, sys: 153 µs, total: 1.47 ms
Wall time: 3.49 ms


tensor(14)

In [34]:
%%time
""" Matrix multiplication wiht matmul. """
torch.matmul(mat_tensor, mat_tensor)    # faster!!

CPU times: user 421 µs, sys: 49 µs, total: 470 µs
Wall time: 492 µs


tensor(14)

In [35]:
""" Shape calculation common error. 
- The 'matmul' operation works when tensor_B is transposed => torch.matmul(tensor_A, tensor_B will return error
"""
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                        [8, 11], 
                        [9, 12]], dtype=torch.float32)



print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")

### Multiplicate (mm = a shortcut for matmul)
output = torch.mm(tensor_A, tensor_B.T)         
# or ...
#output = torch.matmul(tensor_A, tensor_B.T)   

print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [36]:
""" Create tensor for a Neural Network.
# Since the linear layer always starts with a random weights matrix, let's make it reproducible using matrix multiplication.
""" 
# Allow reproducibility
torch.manual_seed(42) 

linear = torch.nn.Linear(in_features=2,     # in_features = matches inner dimension of input 
                        out_features=6)     # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [37]:
%%time
""" Max min sum ...
N.B.
'print(f"Mean: {x_ten.mean()}")' will return error without the datatype must be specified!
"""
x_ten = torch.arange(0, 100, 10)
print(x_ten)
print(f"Minimum: {x_ten.min()}")
print(f"Maximum: {x_ten.max()}")
print(f"Mean: {x_ten.type(torch.float32).mean()}")
print(f"Sum: {x_ten.sum()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450
CPU times: user 2.41 ms, sys: 282 µs, total: 2.69 ms
Wall time: 12.2 ms


In [38]:
%%time
x_ten = torch.arange(0, 100, 10)
torch.max(x_ten), torch.min(x_ten), torch.mean(x_ten.type(torch.float32)), torch.sum(x_ten)
print(x_ten)
print(f"Minimum: {x_ten.min()}")
print(f"Maximum: {x_ten.max()}")
print(f"Mean: {x_ten.type(torch.float32).mean()}")
print(f"Sum: {x_ten.sum()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450
CPU times: user 2.73 ms, sys: 0 ns, total: 2.73 ms
Wall time: 2.55 ms


### => Passing a tensor to "backward()" as an argument.

The tensor should be a scalar tensor (i.e., a tensor with only one element) that represents the "sensitivity" of the loss <br>
with respect to the output tensor. <br>
The scalar tensor is used to scale the gradients during backpropagation, and it is multiplied with each element <br> of the gradient tensor 
to compute the final gradient. <br>
(Default value when no argument is passed to backward is 1.0.)

In [9]:
""" N.B. 
- v = torch.tensor([0.1,1.0,0.01], dtype=torch.float32) lead to  "RuntimeError: Mismatch in shape!" """
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    v = torch.tensor([0.1], dtype=torch.float32)
    v = torch.tensor(0.1, dtype=torch.float32)
    z.backward(v)

In [40]:
x = torch.randn(1, 3, 4, 2, requires_grad=True)
y = x + 2
z = y * y * 2
z = z.mean(dim=(0, 1, 2, 3))
z

tensor(10.5880, grad_fn=<MeanBackward1>)

In [41]:
""" Create a scalar tensor to scale the gradients. 
N.B.
- 'sensitivity = torch.tensor([0.1], dtype=torch.float32' => not working: Missmatch in shape error!
"""
sensitivitys = torch.ones(x.size())
sensitivityo = torch.ones_like(x)
sensitivitye = torch.empty_like(x)

# Compute the gradients of x with respect to z, scaled by the sensitivity tensor
x.backward(sensitivitye)
x.grad

tensor([[[[3.4918e-34, 0.0000e+00],
          [2.7511e-34, 0.0000e+00],
          [8.9683e-44, 0.0000e+00],
          [2.6905e-43, 0.0000e+00]],

         [[3.5958e-34, 0.0000e+00],
          [1.8777e-43, 0.0000e+00],
          [0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00],
          [7.7052e+31, 7.2148e+22],
          [1.5766e-19, 1.0256e-08],
          [1.6802e-04, 3.0270e+12]]]])

In [42]:
# Create a tensor with the same shape as x but with different values
v_vals = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
v = torch.tensor(v_vals, dtype=torch.float32)
print(v)

if x.size()==v.size(): #callable
    print("x and v => same size")
if x.shape==v.shape:
    print("x and v => same shape")    

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


For example, if v is a 4-dimensional tensor with shape (2, 3, 4, 5), the following slice expressions would produce tensors with different numbers of dimensions:

- v[0]: selects the first batch of data, resulting in a 3-dimensional tensor with shape (3, 4, 5) \
- v[:, 1]: selects the second row of data in all batches, resulting in a 3-dimensional tensor with shape (2, 4, 5) \
- v[0, 1, 2]: selects a single element of the tensor, resulting in a 0-dimensional scalar tensor \
- v[0, :, 1, :]: selects the second column of the second row in the first batch, resulting in a 2-dimensional tensor with shape (4, 5)

In [43]:
x = torch.randn(1, 3, 4, 2, requires_grad=True)
v_vals = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
v = torch.tensor(v_vals, dtype=torch.float32)

if x.size() == v.size():
    print("x and v have the same size")
else:
    print("x and v have different sizes")

if x.shape == v.shape:
    print("x and v have the same shape")
else:
    print("x and v have different shapes")

x and v have different sizes
x and v have different shapes


In [44]:
""" The slice v[0, :, :, :] corresponds to all elements of v in the first dimension (batch size), 
all elements of v in the remaining three dimensions. 
v[0, :, :, :] is a 3D tensor that has the same shape as the last three dimensions of v.
The first dimension (index 0) is usually reserved for the batch size, and the remaining dimensions correspond to the shape of the data.


array created by hands..with same shape as x
values =    [[[[1., 2.], [3., 4.], [5., 6.], [7., 8.]], 
            [[11., 32.], [3., 43.], [53., 6.], [7., 81.]], 
            [[1.1, 2.], [3.3, 41.], [5.2, 62.], [7.1, 84.]]]]
"""
x = torch.randn(1, 3, 4, 2, requires_grad=True)

# Create v with the same shape as x and manually specified values
v = torch.empty_like(x)
# Assign the values of a 4x2 NumPy array to a slice of the PyTorch tensor v
v[0, :, :, :] = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]]) 
v

tensor([[[[1., 2.],
          [3., 4.],
          [5., 6.],
          [7., 8.]],

         [[1., 2.],
          [3., 4.],
          [5., 6.],
          [7., 8.]],

         [[1., 2.],
          [3., 4.],
          [5., 6.],
          [7., 8.]]]])

In [45]:
# Check the shape of x and v
if x.size() == v.size():
    print("x and v have the same size")
else:
    print("x and v have different sizes")
if x.shape == v.shape:
    print("x and v have the same shape")
else:
    print("x and v have different shapes")

x and v have the same size
x and v have the same shape


In [46]:
#### Compute the gradients of x with respect to z, scaled by the sensitivity tensor
z = x.sum()
z.backward(torch.ones_like(z), retain_graph=True) #gradient descent dz/dx
grad = x.grad 
print(grad)

tensor([[[[1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.],
          [1., 1.],
          [1., 1.]]]])


In [47]:
tex = torch.randn(3, requires_grad=True)
tex

tensor([0.7860, 1.0060, 0.8448], requires_grad=True)

In [48]:
a_tensor = tex.sum().backward()
a_tensor

In [49]:
""" detach() method. 
It creates a new tensor yx1 that shares the same data as tex, but is not part of the computation graph 
and has requires_grad=False.
"""
tex.requires_grad_(False) #modify in place with underscore
yx1 = tex.detach() # detached tensor 
print(yx1)
print(tex)
with torch.no_grad(): #computing a tensor yx2 inside a torch.no_grad() context
    yx2 = tex + 2
    print(yx2)

tensor([0.7860, 1.0060, 0.8448])
tensor([0.7860, 1.0060, 0.8448])
tensor([2.7860, 3.0060, 2.8448])


<h2 style="color:#BF66F2 "> Recap: Stochastic Gradient Descent SGD </h2>
<div style="margin-top: -8px;">
SGD is used to find the best set of parameters that minimize the loss function of a model during training to improve its overall performance. <br>

Stochastic means that it uses randomly selected subsets or "batch" of the training data, rather than the full dataset. <br>
Threfore, all processes of computing gradients, updating weights, and resetting gradients to zero is typically repeated multiple times <br> during training to optimize the model parameters. <br>
E.G. => Between epochs i need to reset to avoid errors...<br>
<div style="margin-top: -12px;">

- tensor([3., 3., 3., 3.]) <br>
- tensor([6., 6., 6., 6.]) <br>
- tensor([9., 9., 9., 9.]) <br>
- tensor([12., 12., 12., 12.]) <br>

An SGD optimizer updates the values of weights during training, trying to adjust the values of the model parameters based on the <br> gradients of the loss function, with respect to the parameters. <br>
Its goal is to find the set of parameter values that minimize the loss function, which corresponds to the best fit of the model  <br>
to the training data.
</div>
</div>

In [50]:
""" SGD optimizer.
N.B.1 
1) Declaring the SGD => torch.optim.SGD(weights, lr=0.01) without brakets [...] lead to an error! 
    (weights is a tensor and not an iterable of tensors)
N.B.2
The 'step()' method updates the weights and then call the zero_grad() method to reset the gradients to zero.   
"""
weights = torch.ones(4, requires_grad=True)

for epoch in range(4):
    model_output = (weights * 3).sum(dim=0)
    model_output.backward()
    print(weights.grad)

    weights.grad.zero_() 

optimizer = torch.optim.SGD([weights], lr=0.01) 
# Update weights (model parameters) according to the gradients computed during backpropagation.
optimizer.step() 
# Reset gradient
optimizer.zero_grad() 

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [51]:
""" Simple gradient descent with no bias involved. """
x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0, requires_grad=True)

# Forward pass
y_hat = w * x 
###Calculate Loss
loss = (y_hat - y).pow(2) 
# or ...
#loss = (y_hat - y)**2

# Backward pass
loss.backward() 
# Loss
print(loss)
# First gradient of w
print(w.grad)

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


<h3 style="color:#BF66F2 ">  Recap: Scaling Tradeoff </h3>
<div style="margin-top: -8px;">
Larger weights can lead to more complex models with higher capacity, but can also be more prone to overfitting and require more careful regularization.
</div>

In [52]:
"""  Scale he weights by a factor of 3.
It can be a useful to increase the magnitude of the weights.
N.B.1
'model_output' is obtained by:
    - scaling the weights by a factor of 3 ;
    - sums up the resulting tensor along the first dimension (so 0, the columns);
    - effectively collapsing the tensor to a scalar value ;
N.B.2
last cell
"""
weights = torch.ones(4, requires_grad=True)

for epoch in range(114):
    model_output = torch.relu(weights * 3).sum(dim=0) 
    model_output.backward()
    print(weights.grad)

    weights.grad.zero_() 

optimizer = torch.optim.SGD([weights], lr=0.01) 
optimizer.step()
optimizer.zero_grad()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
