<div style="line-height:1.2;">

<h1 style="color:#BF66F2; margin-bottom: 0.3em;">PyTorch basics 1</h1>

<h4 style="margin-top: 0.3em; margin-bottom: 1em;">Tensors, Data Loaders, and Training models.</h4>

<div style="line-height:1.4; margin-bottom: 0.5em;">
    <h3 style="color: lightblue; display: inline; margin-right: 0.5em;">Keywords:</h3>
    ToTensor + %%capture magic + multiplication with @ + itertools islice() + torch utils
</div>

</div>

In [1]:
# Set autocompletion in Colab
#!pip install jedi
%config Completer.use_jedi = True

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import itertools

import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

<h2 style="color:#BF66F2 ">  Tensors </h2>

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [5]:
# Retain the properties of x_data
x_ones = torch.ones_like(x_data)
# Override the datatype of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float)

print(f"Ones Tensor: \n {x_ones} \n")
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3340, 0.7459],
        [0.5554, 0.3782]]) 



In [6]:
""" Tensors with random or constant values.
N.B.
'shape' is a tuple of tensor dimensions, it determines the dimensionality of the output tensor.
"""
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5918, 0.6355, 0.4791],
        [0.8259, 0.6885, 0.2902]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
# Tensor attributes that describe their shape, datatype, and the device on which they are stored.
tens1 = torch.rand(3, 4)

print(f"Shape of tensor: {tens1.shape}")
print(f"Datatype of tensor: {tens1.dtype}")
print(f"Device tensor is stored on: {tens1.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


<h3 style="color:#BF66F2 ">  Tensors operations </h3>
Transposing, indexing, slicing, mathematical operations, linear algebra, random sampling...

In [8]:
# Move tensor to the GPU, if available
if torch.cuda.is_available():
    tensor = tens1.to('cuda')
    print(f"Device tensor is stored on: {tens1.device}")
else:
    tensor = tens1

Device tensor is stored on: cpu


In [ ]:
tens2 = torch.ones(4, 4)
tens2[:,1] = 0
print(tens2)

tens3 = torch.ones(4, 4)
tens3[:,1] = 3
print(tens3)
tens4 = torch.ones(4, 4)
tens4[:,1] = 4
print(tens4)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.]])
tensor([[1., 4., 1., 1.],
        [1., 4., 1., 1.],
        [1., 4., 1., 1.],
        [1., 4., 1., 1.]])


In [ ]:
""" Join Tensors """
t1 = torch.cat([tens2, tens2, tens2], dim=1)
t2 = torch.cat([tens2, tens3, tens3], dim=0)

print(t1)
print(t2)


tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.]])


In [ ]:
""" Multiplicate tensors """
### Calculate Element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# or ...
print(f"tensor * tensor \n {tensor * tensor}")

# Computes the matrix multiplication between two tensors
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")

# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.mul(tensor) 
 tensor([[0.1269, 0.1964, 0.3367, 0.3216],
        [0.7815, 0.4894, 0.0585, 0.1033],
        [0.0043, 0.9682, 0.1127, 0.1043]]) 

tensor * tensor 
 tensor([[0.1269, 0.1964, 0.3367, 0.3216],
        [0.7815, 0.4894, 0.0585, 0.1033],
        [0.0043, 0.9682, 0.1127, 0.1043]])
tensor.matmul(tensor.T) 
 tensor([[0.9815, 0.9474, 0.8373],
        [0.9474, 1.4327, 0.9311],
        [0.8373, 0.9311, 1.1895]]) 

tensor @ tensor.T 
 tensor([[0.9815, 0.9474, 0.8373],
        [0.9474, 1.4327, 0.9311],
        [0.8373, 0.9311, 1.1895]])


In [ ]:
""" In-place operations Operations that have a _ suffix are in-place operations.
For example: x.copy_(y), x.t_(), will change x. """

print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[0.3562, 0.4432, 0.5803, 0.5671],
        [0.8840, 0.6996, 0.2418, 0.3213],
        [0.0653, 0.9840, 0.3358, 0.3230]]) 

tensor([[5.3562, 5.4432, 5.5803, 5.5671],
        [5.8840, 5.6996, 5.2418, 5.3213],
        [5.0653, 5.9840, 5.3358, 5.3230]])


In [ ]:
tz = torch.ones(5)
print(f"tz is : {tz}")
nz = tz.numpy()
print(f"nz is : {nz}")
print("type n is {}".format(type(nz)))

tz is : tensor([1., 1., 1., 1., 1.])
nz is : [1. 1. 1. 1. 1.]
type n is <class 'numpy.ndarray'>


In [ ]:
""" Add 1 to each element.
N.B.
=> also the numpy array 'nz' change! """
tz.add_(1)
print(f"tz new: {tz}")
print(f"nz new: {nz}")  # also the ndarray change!

tz new: tensor([2., 2., 2., 2., 2.])
nz new: [2. 2. 2. 2. 2.]


In [ ]:
""" Add 4 to each element.
N.B.
=> also the tensor 't' change! """
np.add(nz, 4, out=nz)
print(f"t: {tz}")
print(f"n: {nz}")

t: tensor([6., 6., 6., 6., 6.])
n: [6. 6. 6. 6. 6.]


<h2 style="color:#BF66F2 ">  Datasets </h2>

In [ ]:
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
)

In [ ]:
print(type(training_data))
print()
print(training_data)

<class 'torchvision.datasets.mnist.FashionMNIST'>

Dataset FashionMNIST
    Number of datapoints: 60000
    Root location: data
    Split: Train
    StandardTransform
Transform: ToTensor()


In [ ]:
# Get the number of samples in the dataset
dataset_size = len(training_data)
sample = training_data[0]
sample_size = sample[0].size()

print(dataset_size)
print(sample_size)
print(training_data[0][0][0][0])

60000
torch.Size([1, 28, 28])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])


<h2 style="color:#BF66F2 ">  Training </h2>

<h3 style="color:#BF66F2 ">  Recap: </h3>
<div style="margin-top:-8px;">
The DataLoader class takes a PyTorch dataset object and returns an iterator that can be used to iterate over the given dataset in batches of a specified size.
</div>

In [ ]:
## Create DataLoaders
train_ds = DataLoader(training_data, batch_size=64)
test_ds = DataLoader(test_data, batch_size=64)

In [ ]:
for X, y in test_ds:
    print(f"Shape of X [N,C,H,W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

Shape of X [N,C,H,W]: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64]) torch.int64


In [ ]:
train_ds

In [ ]:
training_data

Dataset FashionMNIST
    Number of datapoints: 60000
    Root location: data
    Split: Train
    StandardTransform
Transform: ToTensor()

DataLoader options:
<div style="margin-top: -18px;">
    
- dataset
- batch_size (int): how many samples per batch to load (default: 1)
- shuffle (bool): to reshuffle in every epoch (default: False)
- sampler (Sampler or Iterable): defines the strategy to draw
- batch_sampler (Sampler or Iterable): like :attr:'sampler', but
    returns a batch of indices at a time.
- num_workers (int): how many subprocesses to use for data loading.
- collate_fn (Callable): merges a list of samples to form a
    mini-batch of Tensor(s).
- pin_memory (bool): If True, the data loader will copy Tensors
    into device/CUDA pinned memory before returning them.
- drop_last (bool): set to True to drop the last incomplete batch,
    if the dataset size is not divisible by the batch size.
- timeout (numeric): if positive, the timeout value for collecting a batch from workers.
- worker_init_fn (Callable): If not ''None'', this will be called on each worker subprocess with the worker id.
- generator (torch.Generator): If not None, RandomSampler will generate
random indexes and multiprocessing <br> to generate 'base_seed' for workers.
</div>        

<h3 style="color:#BF66F2 ">  Recap: </h3>
<div style="margin-top: -8px;">
%%capture magic <br>
Used to capture the output and prevent it from being displayed.
</div>

In [ ]:
%%capture magic
""" Get a list of tuples, where each tuple represents a single sample in the test_data dataset.
The first element of each tuple is the image tensor and the second element is the label tensor.
"""
print(list(torch.utils.data.DataLoader(test_data)))

In [ ]:
%config NotebookApp.iopub_data_rate_limit=100000000

print(list(torch.utils.data.DataLoader(test_data[0][0][0][0])))

[tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.])]


<h3 style="color:#BF66F2 ">  Recap: </h3>
<div style="margin-top: -8px;">
Itertools islice() method can be used to slice an iterable in a manner similar to lists, but without actually converting the iterable to a list.
</div>

In [ ]:
""" Create DataLoader and slice it """
data_loader = torch.utils.data.DataLoader(test_data)
res = list(itertools.islice(data_loader, 5))
print(res[0][0][0][0][0])

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])


In [ ]:
for batch in data_loader:
    print(batch[0][0][0][:2])
    break

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.]])


In [ ]:
flattened_data = list(itertools.chain(*data_loader))
flattened_data[0][0][0][0]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])

In [ ]:
num_samples = len(list(itertools.chain(*data_loader)))
num_samples

20000

In [ ]:
""" last cell """
for i, batch in enumerate(data_loader):
    print(f"Batch {i}: {batch}")
    if i==3:
        break

Batch 0: [tensor([[[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000